package com.myfriendkennyagent.museportal.protocol.noise

import com.myfriendkennyagent.museportal.protocol.Bytes
import com.myfriendkennyagent.museportal.protocol.TestSupport
import org.json.JSONArray
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertThrows
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Byte-for-byte interop with Meta's Python reference, using the vectors in
 * `vectors/noise_reference.json` (generated by `tools/gen_protocol_vectors.py`).
 */
class NoiseReferenceTest {
  private val v = TestSupport.json("vectors/noise_reference.json")
  private val keys = v.getJSONObject("keys")
  private val chunkId = v.getLong("chunk_id")

  private fun key(name: String) = X25519KeyPair(Bytes.unhex(keys.getString(name)))

  private fun hexes(array: JSONArray): List<String> = (0 until array.length()).map { array.getString(it) }

  private class Handshake(
    val initiator: NoiseXXInitiator,
    val responder: NoiseXXResponder,
    val msg1: ByteArray,
    val msg2: ByteArray,
    val msg3: ByteArray,
    val payload: ByteArray,
  )

  private fun handshake(): Handshake {
    val initiatorKeys = ArrayDeque(listOf(key("initiator_e"), key("initiator_s")))
    val responderKeys = ArrayDeque(listOf(key("responder_e"), key("responder_s")))
    val initiator = NoiseXXInitiator { initiatorKeys.removeFirst() }
    val responder = NoiseXXResponder(Bytes.unhex(v.getString("responder_payload"))) { responderKeys.removeFirst() }
    initiator.initialize()
    responder.initialize()
    val msg1 = initiator.writeMessage1()
    val msg2 = responder.readMessage1AndWriteMessage2(msg1)
    val payload = initiator.readMessage2(msg2)
    val msg3 = initiator.writeMessage3()
    responder.readMessage3(msg3)
    return Handshake(initiator, responder, msg1, msg2, msg3, payload)
  }

  @Test
  fun `handshake messages match the reference`() {
    val h = handshake()
    assertEquals(v.getString("msg1"), Bytes.hex(h.msg1))
    assertEquals(v.getString("msg2"), Bytes.hex(h.msg2))
    assertEquals(v.getString("msg3"), Bytes.hex(h.msg3))
    assertEquals(v.getString("responder_payload"), Bytes.hex(h.payload))
    assertEquals(v.getString("handshake_hash"), Bytes.hex(h.initiator.handshakeHash()))
    assertEquals(v.getString("handshake_hash"), Bytes.hex(h.responder.handshakeHash()))
  }

  @Test
  fun `transport frames match the reference`() {
    val h = handshake()
    val (send, recv) = h.initiator.split()
    val device = NoiseTransport(send, recv) { chunkId }

    val control = device.startStreamRequest("POST", "/link-control")
    val expectedControl = v.getJSONObject("device_open_control")
    assertEquals(expectedControl.getLong("stream_id"), control.streamId)
    assertEquals(hexes(expectedControl.getJSONArray("frames")), control.frames.map(Bytes::hex))

    val register = Bytes.unhex(v.getString("register_message"))
    assertEquals(hexes(v.getJSONArray("device_register_body")), device.encryptBodyChunk(control.streamId, register).map(Bytes::hex))

    val chat =
      device.encryptHttpRequest(
        "POST",
        "/chat/stream",
        """{"message":"hi"}""".toByteArray(),
        listOf(Header("Content-Type", "application/json"), Header("x-app-id", "musegadget")),
      )
    val expectedChat = v.getJSONObject("device_chat_request")
    assertEquals(expectedChat.getLong("stream_id"), chat.streamId)
    assertEquals(hexes(expectedChat.getJSONArray("frames")), chat.frames.map(Bytes::hex))

    assertEquals(hexes(v.getJSONArray("device_chat_reset")), device.encryptReset(chat.streamId, "cancelled").map(Bytes::hex))
  }

  @Test
  fun `device decrypts the reference VM response`() {
    val h = handshake()
    val (send, recv) = h.initiator.split()
    val device = NoiseTransport(send, recv)
    val frames = hexes(v.getJSONArray("vm_control_response")).map(Bytes::unhex)
    val decoded = frames.mapNotNull { device.decryptFrame(it) }
    assertEquals(1, decoded.size)
    val response = decoded[0].value as ApplicationResponse
    assertEquals(1L, decoded[0].streamId)
    assertEquals(200, response.status)
    assertArrayEquals(byteArrayOf(2, 0, 0, 0, '{'.code.toByte(), '}'.code.toByte()), response.body)
  }

  @Test
  fun `responder and initiator agree on transport keys`() {
    val h = handshake()
    val (iSend, iRecv) = h.initiator.split()
    val (rSend, rRecv) = h.responder.split()
    val msg = "ping".toByteArray()
    assertArrayEquals(msg, rRecv.decryptWithAd(ByteArray(0), iSend.encryptWithAd(ByteArray(0), msg)))
    assertArrayEquals(msg, iRecv.decryptWithAd(ByteArray(0), rSend.encryptWithAd(ByteArray(0), msg)))
  }

  @Test
  fun `envelope encodings match the reference`() {
    val s = v.getJSONObject("samples")
    val request =
      Envelope.encodeServiceRequest(
        ServiceRequest(
          ServiceType.DAEMON,
          Envelope.encodeServiceFrame(
            ServiceFrame(
              7,
              ApplicationRequest(
                "POST",
                "/chat/subscribe",
                listOf(Header("accept", "application/x-ndjson")),
                "{}".toByteArray(),
                endBody = true,
              ),
            )
          ),
        )
      )
    assertEquals(s.getString("service_request_with_headers"), Bytes.hex(request))
    assertEquals(
      s.getString("service_frame_negative_stream"),
      Bytes.hex(Envelope.encodeServiceFrame(ServiceFrame(-5, BodyChunk("x".toByteArray(), true)))),
    )
    assertEquals(
      s.getString("service_frame_reset"),
      Bytes.hex(Envelope.encodeServiceFrame(ServiceFrame(3, Reset(ResetCode.TIMEOUT, "slow")))),
    )
    assertEquals(
      s.getString("service_frame_response_negative_status"),
      Bytes.hex(
        Envelope.encodeServiceFrame(ServiceFrame(9, ApplicationResponse(-1, listOf(Header("k", "v")), ByteArray(0), true)))
      ),
    )
    val big = ByteArray(256 * 300) { (it % 256).toByte() }
    assertEquals(hexes(s.getJSONArray("noise_frames_two_chunks")), NoiseFraming.encodeFrames(big, -2).map(Bytes::hex))
  }

  @Test
  fun `envelopes round trip`() {
    val decoded = NoiseTransport.decodeRequestEnvelope(Bytes.unhex(v.getJSONObject("samples").getString("service_request_with_headers")))
    val req = decoded.second.value as ApplicationRequest
    assertEquals(7L, decoded.second.streamId)
    assertEquals("/chat/subscribe", req.path)
    assertEquals(listOf(Header("accept", "application/x-ndjson")), req.headers)
    assertTrue(req.endBody)

    val reset = Envelope.decodeServiceFrame(Envelope.encodeServiceFrame(ServiceFrame(-1, Reset(ResetCode.CANCELLED, "x"))))
    assertEquals(-1L, reset.streamId)
    assertEquals(ResetCode.CANCELLED, (reset.value as Reset).code)
  }

  @Test
  fun `decoder reassembles chunks and rejects bad input`() {
    val big = ByteArray(NoiseFraming.MAX_CHUNK_PAYLOAD * 2 + 10) { it.toByte() }
    val frames = NoiseFraming.encodeFrames(big, 99)
    assertEquals(3, frames.size)
    val decoder = NoiseFrameDecoder()
    assertNull(decoder.decode(frames[0]))
    assertNull(decoder.decode(frames[1]))
    assertArrayEquals(big, decoder.decode(frames[2]))

    val dup = NoiseFrameDecoder()
    dup.decode(frames[0])
    assertThrows(IllegalArgumentException::class.java) { dup.decode(frames[0]) }
    // Poisoned after a failure, as upstream.
    assertThrows(IllegalStateException::class.java) { dup.decode(frames[1]) }

    val bad = NoiseFraming.encodeFrame(NoiseTransportFrame(1, 5, 2, byteArrayOf(1)))
    assertThrows(IllegalArgumentException::class.java) { NoiseFrameDecoder().decode(bad) }
  }

  @Test
  fun `tampered ciphertext poisons the cipher`() {
    val h = handshake()
    val (iSend, _) = h.initiator.split()
    val (_, rRecv) = h.responder.split()
    val ct = iSend.encryptWithAd(ByteArray(0), "hello".toByteArray())
    ct[0] = (ct[0].toInt() xor 1).toByte()
    assertThrows(NoiseProtocolException::class.java) { rRecv.decryptWithAd(ByteArray(0), ct) }
    assertThrows(NoiseProtocolException::class.java) { rRecv.decryptWithAd(ByteArray(0), ct) }
  }

  @Test
  fun `low order public keys are rejected`() {
    val initiator = NoiseXXInitiator()
    initiator.initialize()
    initiator.writeMessage1()
    val msg2 = ByteArray(NoiseXX.MIN_MSG2_LEN) // all-zero ephemeral key
    assertThrows(NoiseProtocolException::class.java) { initiator.readMessage2(msg2) }
    assertThrows(NoiseProtocolException::class.java) { initiator.writeMessage3() }
  }

  @Test
  fun `proto rejects malformed input`() {
    assertThrows(ProtoException::class.java) { Envelope.decodeServiceFrame(byteArrayOf(0x08)) } // truncated varint
    assertThrows(ProtoException::class.java) { Envelope.decodeServiceFrame(byteArrayOf(0x12, 0x05, 0x01)) } // truncated
    assertThrows(ProtoException::class.java) { Envelope.decodeServiceFrame(byteArrayOf(0x00)) } // field 0
    assertThrows(ProtoException::class.java) { Envelope.decodeServiceFrame(byteArrayOf(0x0a, 0x00)) } // wrong wire type
  }
}
