#!/usr/bin/env python3
"""Generate interop vectors from Meta's reference Linux Device SDK.

Runs the SDK's own Noise XX, framing and envelope code with fixed keys and
chunk ids, and records every byte, so the Kotlin port is checked against
the reference implementation rather than against itself.

    python3 tools/gen_protocol_vectors.py /path/to/muse-gadget-sdk \
        > protocol/src/test/resources/vectors/noise_reference.json

Needs the `cryptography` package. Public synthetic data only.
"""

import json
import sys
from pathlib import Path

sdk = Path(sys.argv[1]).resolve()
sys.path.insert(0, str(sdk / "linux" / "src"))

from cryptography.hazmat.primitives import serialization  # noqa: E402
from cryptography.hazmat.primitives.asymmetric import x25519  # noqa: E402

from musegadget.link_client import encode_message  # noqa: E402
from musegadget.noise import framing, noise_xx  # noqa: E402
from musegadget.noise.envelope import (  # noqa: E402
    ApplicationRequest,
    ApplicationResponse,
    BodyChunk,
    Header,
    Reset,
    ResetCode,
    ServiceFrame,
    ServiceRequest,
    ServiceType,
    encode_service_frame,
    encode_service_request,
)
from musegadget.noise.transport import NoiseTransport, encode_response_envelope  # noqa: E402

KEYS = {
    "initiator_e": bytes([0x11] * 32),
    "responder_e": bytes([0x33] * 32),
    "responder_s": bytes([0x44] * 32),
    "initiator_s": bytes([0x22] * 32),
}
# Order in which the reference code asks for keys during a handshake.
ORDER = ["initiator_e", "responder_e", "responder_s", "initiator_s"]
queue = [KEYS[name] for name in ORDER]


def fixed_pair():
    raw = queue.pop(0)
    private = x25519.X25519PrivateKey.from_private_bytes(raw)
    public = private.public_key().public_bytes(
        encoding=serialization.Encoding.Raw, format=serialization.PublicFormat.Raw
    )
    return noise_xx._X25519KeyPair(private_key=private, public_key_bytes=public)


noise_xx._generate_x25519_key_pair = fixed_pair
CHUNK_ID = 0x0102030405060708
framing._random_int64 = lambda: CHUNK_ID

payload = b"vm-hello"
initiator = noise_xx.NoiseXXInitiator()
responder = noise_xx.NoiseXXResponder(payload)
initiator.initialize()
responder.initialize()
msg1 = initiator.write_message1()
msg2 = responder.read_message1_and_write_message2(msg1)
got_payload = initiator.read_message2(msg2)
msg3 = initiator.write_message3()
responder.read_message3(msg3)
handshake_hash = initiator.handshake_hash()
assert handshake_hash == responder.handshake_hash()
i_send, i_recv = initiator.split()
r_send, r_recv = responder.split()

device = NoiseTransport(i_send, i_recv)
control = device.start_stream_request("POST", "/link-control")
register = encode_message({"type": "req", "id": "reg-1", "method": "link.register", "params": {"node_id": "homelink-000001"}})
body = device.encrypt_body_chunk(control.stream_id, register)
chat = device.encrypt_http_request(
    "POST", "/chat/stream", b'{"message":"hi"}',
    headers=[Header("Content-Type", "application/json"), Header("x-app-id", "musegadget")],
)
reset = device.encrypt_reset(chat.stream_id, reason="cancelled")

# VM side: a response on the control stream, as the VM would send it.
response_plain = encode_response_envelope(
    ServiceFrame.response(control.stream_id, ApplicationResponse(status=200, body=b"\x02\x00\x00\x00{}", end_body=False))
)
vm_frames = [r_send.encrypt_with_ad(b"", f) for f in framing.encode_noise_frames(response_plain)]

samples = {
    "service_request_with_headers": encode_service_request(
        ServiceRequest(
            service=ServiceType.SERVICE_DAEMON,
            payload=encode_service_frame(
                ServiceFrame.request(7, ApplicationRequest(
                    verb="POST", path="/chat/subscribe",
                    headers=[Header("accept", "application/x-ndjson")], body=b"{}", end_body=True,
                ))
            ),
        )
    ),
    "service_frame_negative_stream": encode_service_frame(ServiceFrame.body_chunk(-5, BodyChunk(data=b"x", end_body=True))),
    "service_frame_reset": encode_service_frame(ServiceFrame.reset(3, Reset(code=ResetCode.TIMEOUT, reason="slow"))),
    "service_frame_response_negative_status": encode_service_frame(
        ServiceFrame.response(9, ApplicationResponse(status=-1, headers=[Header("k", "v")], body=b"", end_body=True))
    ),
    "noise_frames_two_chunks": [f.hex() for f in framing.encode_noise_frames(bytes(range(256)) * 300, chunk_id=-2)],
}

hexed = lambda frames: [f.hex() for f in frames]  # noqa: E731
print(json.dumps({
    "note": "Generated by tools/gen_protocol_vectors.py from the Muse Gadget SDK Linux reference. Synthetic keys only.",
    "keys": {name: KEYS[name].hex() for name in ORDER},
    "chunk_id": CHUNK_ID,
    "responder_payload": payload.hex(),
    "msg1": msg1.hex(),
    "msg2": msg2.hex(),
    "msg3": msg3.hex(),
    "handshake_hash": handshake_hash.hex(),
    "device_open_control": {"stream_id": control.stream_id, "frames": hexed(control.frames)},
    "device_register_body": hexed(body),
    "register_message": register.hex(),
    "device_chat_request": {"stream_id": chat.stream_id, "frames": hexed(chat.frames)},
    "device_chat_reset": hexed(reset),
    "vm_control_response": hexed(vm_frames),
    "samples": {k: (v.hex() if isinstance(v, bytes) else v) for k, v in samples.items()},
}, indent=1))
